
package nieruchomosci.biuro;

import com.nieruchomosci.biuro.biuroniruchomoscitest.BazaBiura;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DodawanieOferty extends javax.swing.JPanel {
    BazaBiura _db;
    BiuroNieruchomosci _bn;
    server _server;
    
    public DodawanieOferty(BazaBiura db,int ID,BiuroNieruchomosci bn) {
        _db=db;
        _bn=bn;
       
        initComponents();
        //jPanel1.setVisible(false);
       // jPanel2.setVisible(false);
        int i=0;
       String transakcja[]=new String[]{"Wybierz transakcje","Sprzedaz", "Wynajem", "Zamiana"};
        for(i=0;i<transakcja.length;i++){
            Transakcja.addItem(transakcja[i]);
        }
        String wojewodztwa[]=new String[]{"Wybierz wojewodztwo","Dolno�l�skie","Kujawsko-Pomorskie",
                                          "Lubelskie","Lubuskie","��dzkie",
                                          "Ma�opolskie","Mazowieckie","Opolskie","Podkarpackie",
                                          "Podlaskie","Pomorskie","�l�skie","�wi�tokrzyskie",
                                          "Warmi�sko-Mazurskie","Wielkopolskie","Zachodniopomorskie"};
        for(i=0;i<wojewodztwa.length;i++){
            wojewodztwo.addItem(wojewodztwa[i]);
        }
        String wlasnosc[]=new String[]{"Wybierz rodzaj własności","Spółdzielcze Własnościowe", "Własnościowe", "Hipoteka"};
        for(i=0;i<wlasnosc.length;i++){
            rodzajWlasnosci.addItem(wlasnosc[i]);
        }
    }

    public DodawanieOferty(server server,int ID,BiuroNieruchomosci bn) {
        _server=server;
        _bn=bn;
       
        initComponents();
        //jPanel1.setVisible(false);
       // jPanel2.setVisible(false);
        int i=0;
       String transakcja[]=new String[]{"Wybierz transakcje","Sprzedaż", "Wynajem", "Zamienią"};
        for(i=0;i<transakcja.length;i++){
            Transakcja.addItem(transakcja[i]);
        }
        String wojewodztwa[]=new String[]{"Wybierz wojewodztwo","Dolnośląskie","Kujawsko-Pomorskie",
                                          "Lubelskie","Lubuskie","�?ódzkie",
                                          "Małopolskie","Mazowieckie","Opolskie","Podkarpackie",
                                          "Podlaskie","Pomorskie","Śląskie","Świętokrzyskie",
                                          "Warmińsko-Mazurskie","Wielkopolskie","Zachodniopomorskie"};
        for(i=0;i<wojewodztwa.length;i++){
            wojewodztwo.addItem(wojewodztwa[i]);
        }
        String wlasnosc[]=new String[]{"Wybierz rodzaj własności","Spółdzielcze Własnościowe", "Własnościowe", "Hipoteka"};
        for(i=0;i<wlasnosc.length;i++){
            rodzajWlasnosci.addItem(wlasnosc[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Transakcja = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Czynsz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pow_calkowita = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pietro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ilosc_pieter = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rok_budowy = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        wojewodztwo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        panstwo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dzielnicaWies = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ulica = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rodzajWlasnosci = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        stanTechniczny = new javax.swing.JTextField();
        okna = new javax.swing.JTextField();
        ogrzewanie = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lazienka = new javax.swing.JTextField();
        wc = new javax.swing.JTextField();
        Kuchnia = new javax.swing.JCheckBox();
        Garaz = new javax.swing.JCheckBox();
        MiejsceParkingowe = new javax.swing.JCheckBox();
        Piwnica = new javax.swing.JCheckBox();
        Balkon = new javax.swing.JCheckBox();
        Winda = new javax.swing.JCheckBox();
        Zsyp = new javax.swing.JCheckBox();
        Umeblowanie = new javax.swing.JCheckBox();
        cieplaWoda = new javax.swing.JCheckBox();
        DodajOferte = new javax.swing.JButton();

        jLabel1.setText("Dodawanie Oferty");

        jLabel2.setText("Transakcja");

        jLabel3.setText("Czynsz");

        Czynsz.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Czynsz.setText("0.0");
        Czynsz.setToolTipText("");

        jLabel4.setText("Pow całkowita(m2)");

        pow_calkowita.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pow_calkowita.setText("0.0");

        jLabel5.setText("Piętro");

        pietro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pietro.setText("0");

        jLabel6.setText("Ilość pięter");

        Ilosc_pieter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Ilosc_pieter.setText("0");

        jLabel7.setText("Rok budowy");

        rok_budowy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rok_budowy.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adres"));

        jLabel9.setText("Wojewódźtwo");

        jLabel8.setText("Państwo");

        panstwo.setText("Polska");

        jLabel11.setText("Dzielnica/Wieś");

        jLabel12.setText("Ulica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dzielnicaWies))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(wojewodztwo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panstwo)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel12)
                    .addGap(56, 56, 56)
                    .addComponent(ulica)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(panstwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(wojewodztwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dzielnicaWies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ulica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Szczegóły"));

        jLabel13.setText("Rodzaj Własności");

        jLabel14.setText("Stan techniczny");

        jLabel15.setText("Okna");

        jLabel16.setText("Ogrzewanie");

        jLabel18.setText("�?azienka");

        jLabel19.setText("WC");

        Kuchnia.setText("Kuchnia");

        Garaz.setText("Garaż");

        MiejsceParkingowe.setText("Miejsce parkingowe");

        Piwnica.setText("Piwnica");

        Balkon.setText("Balkon");

        Winda.setText("Winda");

        Zsyp.setText("Zsyp");

        Umeblowanie.setText("Umeblowanie");

        cieplaWoda.setText("Ciepła woda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rodzajWlasnosci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MiejsceParkingowe)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Winda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(Balkon)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Umeblowanie)
                            .addComponent(Zsyp)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(Kuchnia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Garaz)
                                .addGap(18, 18, 18)
                                .addComponent(Piwnica)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(55, 55, 55))
                            .addComponent(okna)
                            .addComponent(stanTechniczny, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ogrzewanie)
                            .addComponent(lazienka, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wc, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cieplaWoda)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rodzajWlasnosci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(stanTechniczny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(okna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ogrzewanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(lazienka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(wc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kuchnia)
                    .addComponent(Garaz)
                    .addComponent(Piwnica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MiejsceParkingowe)
                    .addComponent(Umeblowanie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Balkon)
                    .addComponent(Winda)
                    .addComponent(Zsyp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addComponent(cieplaWoda))
        );

        DodajOferte.setText("Dodaj Ofertę");
        DodajOferte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DodajOferteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Transakcja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Czynsz, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ilosc_pieter)
                                    .addComponent(pietro)
                                    .addComponent(pow_calkowita)
                                    .addComponent(rok_budowy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajOferte))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DodajOferte))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Transakcja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Czynsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pow_calkowita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pietro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Ilosc_pieter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rok_budowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DodajOferteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DodajOferteMouseClicked
        // TODO add your handling code here:
        boolean flaga=true;
        if( Czynsz.getText().equals("0.0") || Czynsz.getText().equals("") ){
            Czynsz.setFocusable(true);
        Czynsz.grabFocus();
        flaga=false;
        }else if( pow_calkowita.getText().equals("0.0") || pow_calkowita.getText().equals("") ){
        pow_calkowita.setFocusable(true);
        pow_calkowita.grabFocus();
        flaga=false;
        }else if( Ilosc_pieter.getText().equals("0") || Ilosc_pieter.getText().equals("") ){
        Ilosc_pieter.setFocusable(true);
        Ilosc_pieter.grabFocus();
        flaga=false;
        }else if( pietro.getText().equals("0") || pietro.getText().equals("") ){
        pietro.setFocusable(true);
        pietro.grabFocus();
        flaga=false;
        }else if( rok_budowy.getText().equals("0") || rok_budowy.getText().equals("") ){
        rok_budowy.setFocusable(true);
        rok_budowy.grabFocus();
        flaga=false;
        }else if( dzielnicaWies.getText().equals("") ){
        dzielnicaWies.setFocusable(true);
        dzielnicaWies.grabFocus();
        flaga=false;
        }else if( ulica.getText().equals("") ){
        ulica.setFocusable(true);
        ulica.grabFocus();
        flaga=false;
        }else if( stanTechniczny.getText().equals("") ){
        stanTechniczny.setFocusable(true);
        stanTechniczny.grabFocus();
        flaga=false;
        }else if( okna.getText().equals("") ){
        okna.setFocusable(true);
        okna.grabFocus();
        flaga=false;
        }else if(lazienka.getText().equals("") ){
        lazienka.setFocusable(true);
        lazienka.grabFocus();
        flaga=false;
        }else if( wc.getText().equals("") ){
        wc.setFocusable(true);
        wc.grabFocus();
        flaga=false;
        }else if( ogrzewanie.getText().equals("") ){
        ogrzewanie.setFocusable(true);
        ogrzewanie.grabFocus();
        flaga=false;
        }else {
            
            try{
            _bn.server.Add_oferta(_bn.getIDUser(),Transakcja.getSelectedItem().toString(),Double.parseDouble(Czynsz.getText()),Double.parseDouble(pow_calkowita.getText()),Integer.parseInt(pietro.getText()),Integer.parseInt(Ilosc_pieter.getText()),Integer.parseInt(rok_budowy.getText()) );               // _server.Add_oferta(int lb);    
            _bn.server.Add_adres(panstwo.getText(),wojewodztwo.getSelectedItem().toString(),dzielnicaWies.getText(),ulica.getText());
            _bn.server.Add_szczegoly(rodzajWlasnosci.getSelectedItem().toString(),stanTechniczny.getText(),okna.getText(),ogrzewanie.getText(),lazienka.getText(),wc.getText(),Kuchnia.isSelected(),Garaz.isSelected(),Piwnica.isSelected(),MiejsceParkingowe.isSelected(),Umeblowanie.isSelected(),Winda.isSelected(),Balkon.isSelected(),Zsyp.isSelected(),cieplaWoda.isSelected());
       
            }catch (Exception ex) {
                try {
                    _db.Add_oferta(_bn.getIDUser(),Transakcja.getSelectedItem().toString(),Double.parseDouble(Czynsz.getText()),Double.parseDouble(pow_calkowita.getText()),Integer.parseInt(pietro.getText()),Integer.parseInt(Ilosc_pieter.getText()),Integer.parseInt(rok_budowy.getText()) );
                    _db.Add_adres(panstwo.getText(),wojewodztwo.getSelectedItem().toString(),dzielnicaWies.getText(),ulica.getText());
                    _db.Add_szczegoly(rodzajWlasnosci.getSelectedItem().toString(),stanTechniczny.getText(),okna.getText(),ogrzewanie.getText(),lazienka.getText(),wc.getText(),Kuchnia.isSelected(),Garaz.isSelected(),Piwnica.isSelected(),MiejsceParkingowe.isSelected(),Umeblowanie.isSelected(),Winda.isSelected(),Balkon.isSelected(),Zsyp.isSelected(),cieplaWoda.isSelected());
                } catch (RemoteException ex1) {
                }
       
            }     
            JOptionPane.showMessageDialog(this, "Doda�e� ofert�");
         this.setVisible(false);
        }
    }//GEN-LAST:event_DodajOferteMouseClicked


        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Balkon;
    private javax.swing.JTextField Czynsz;
    private javax.swing.JButton DodajOferte;
    private javax.swing.JCheckBox Garaz;
    private javax.swing.JTextField Ilosc_pieter;
    private javax.swing.JCheckBox Kuchnia;
    private javax.swing.JCheckBox MiejsceParkingowe;
    private javax.swing.JCheckBox Piwnica;
    private javax.swing.JComboBox Transakcja;
    private javax.swing.JCheckBox Umeblowanie;
    private javax.swing.JCheckBox Winda;
    private javax.swing.JCheckBox Zsyp;
    private javax.swing.JCheckBox cieplaWoda;
    private javax.swing.JTextField dzielnicaWies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lazienka;
    private javax.swing.JTextField ogrzewanie;
    private javax.swing.JTextField okna;
    private javax.swing.JLabel panstwo;
    private javax.swing.JTextField pietro;
    private javax.swing.JTextField pow_calkowita;
    private javax.swing.JComboBox rodzajWlasnosci;
    private javax.swing.JTextField rok_budowy;
    private javax.swing.JTextField stanTechniczny;
    private javax.swing.JTextField ulica;
    private javax.swing.JTextField wc;
    private javax.swing.JComboBox wojewodztwo;
    // End of variables declaration//GEN-END:variables
}
