/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nieruchomosci.biuro.view;

import com.nieruchomosci.biuro.biuroniruchomoscitest.BazaBiura;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.rmi.RemoteException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import nieruchomosci.biuro.server;

/**
 *
 * @author Tomasz
 */
public class Kalendarz extends javax.swing.JPanel {
    BazaBiura _db;
    int _IDuser; 
    nieruchomosci.biuro.server _server;
    /**
     * Creates new form Kalendarz
     * @param db
     * @param user
     */
    public Kalendarz(BazaBiura db,int user) {
        initComponents();
        _db=db;
        _IDuser=user;
        GregorianCalendar nowDate = new GregorianCalendar();
        //jTable2.setVisible(false);
         //table(yearNow,monthNameNow ,dayNow ,dayNameNow);

        this.setLayout(new FlowLayout());
        this.add(new Cal(_IDuser));
        this.repaint();
    //c.add(new Cal());

    }
    public Kalendarz(server server,int user) {
        initComponents();
        _server=server;
        _IDuser=user;
        GregorianCalendar nowDate = new GregorianCalendar();
        //jTable2.setVisible(false);
         //table(yearNow,monthNameNow ,dayNow ,dayNameNow);

        this.setLayout(new FlowLayout());
        this.add(new Cal(_IDuser));
        this.repaint();
    //c.add(new Cal());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown
public class Cal extends JPanel {
  /** The currently-interesting year (not modulo 1900!) */
  protected int yy;

  /** Currently-interesting month and day */
  protected int mm, dd;

  /** The buttons to be displayed */
  protected JButton labs[][];

  /** The number of day squares to leave blank at the start of this month */
  protected int leadGap = 0;

  /** A Calendar object used throughout */
  Calendar calendar = new GregorianCalendar();

  /** Today's year */
  protected final int thisYear = calendar.get(Calendar.YEAR);

  /** Today's month */
  protected final int thisMonth = calendar.get(Calendar.MONTH);

  /** One of the buttons. We just keep its reference for getBackground(). */
  private JButton b0;

  /** The month choice */
  private JComboBox monthChoice;

  /** The year choice */
  private JComboBox yearChoice;

  int user;
  /**
   * Construct a Cal, starting with today.
   */
  Cal(int user) {
    super();
    setYYMMDD(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH),
        calendar.get(Calendar.DAY_OF_MONTH));
    buildGUI();
    this.user=user;
    recompute();
  }

  /**
   * Construct a Cal, given the leading days and the total days
   * 
   * @exception IllegalArgumentException
   *                If year out of range
   */
  Cal(int year, int month, int today) {
    super();
    setYYMMDD(year, month, today);
    buildGUI();
    recompute();
  }

  private void setYYMMDD(int year, int month, int today) {
    yy = year;
    mm = month;
    dd = today;
  }

  String[] months = { "Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec",
      "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień" };

  /** Build the GUI. Assumes that setYYMMDD has been called. */
  private void buildGUI() {
    getAccessibleContext().setAccessibleDescription(
        "Calendar not accessible yet. Sorry!");
    setBorder(BorderFactory.createEtchedBorder());

    setLayout(new BorderLayout());

    JPanel tp = new JPanel();
    tp.add(monthChoice = new JComboBox());
    for (int i = 0; i < months.length; i++)
      monthChoice.addItem(months[i]);
    monthChoice.setSelectedItem(months[mm]);
    monthChoice.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent ae) {
        int i = monthChoice.getSelectedIndex();
        if (i >= 0) {
          mm = i;
          // System.out.println("Month=" + mm);
          recompute();
        }
      }
    });
    monthChoice.getAccessibleContext().setAccessibleName("Months");
    monthChoice.getAccessibleContext().setAccessibleDescription(
        "Choose a month of the year");

    tp.add(yearChoice = new JComboBox());
    yearChoice.setEditable(true);
    for (int i = yy - 5; i < yy + 5; i++)
      yearChoice.addItem(Integer.toString(i));
    yearChoice.setSelectedItem(Integer.toString(yy));
    yearChoice.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent ae) {
        int i = yearChoice.getSelectedIndex();
        if (i >= 0) {
          yy = Integer.parseInt(yearChoice.getSelectedItem()
              .toString());
          // System.out.println("Year=" + yy);
          recompute();
        }
      }
    });
    add(BorderLayout.CENTER, tp);

    JPanel bp = new JPanel();
    bp.setLayout(new GridLayout(7, 7));
    labs = new JButton[6][7]; // first row is days

    bp.add(b0 = new JButton("Nd"));
    bp.add(new JButton("Pon"));
    bp.add(new JButton("Wt"));
    bp.add(new JButton("Śr"));
    bp.add(new JButton("Czw"));
    bp.add(new JButton("Pt"));
    bp.add(new JButton("Sob"));

    ActionListener dateSetter = new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        String num = e.getActionCommand();
        if (!num.equals("")) {
          // set the current day highlighted
          setDayActive(Integer.parseInt(num));
          // When this becomes a Bean, you can
          // fire some kind of DateChanged event here.
          // Also, build a similar daySetter for day-of-week btns.
        }
      }
    };

    // Construct all the buttons, and add them.
    for (int i = 0; i < 6; i++)
      for (int j = 0; j < 7; j++) {
        bp.add(labs[i][j] = new JButton(""));
        labs[i][j].addActionListener(dateSetter);
      }

    add(BorderLayout.SOUTH, bp);
  }

  public int dom[] = { 31, 28, 31, 30, /* jan feb mar apr */
  31, 30, 31, 31, /* may jun jul aug */
  30, 31, 30, 31 /* sep oct nov dec */
  };

  /** Compute which days to put where, in the Cal panel */
  protected void recompute() {
    // System.out.println("Cal::recompute: " + yy + ":" + mm + ":" + dd);
    if (mm < 0 || mm > 11)
      throw new IllegalArgumentException("Month " + mm
          + " bad, must be 0-11");
    clearDayActive();
    calendar = new GregorianCalendar(yy, mm, dd);

    // Compute how much to leave before the first.
    // getDay() returns 0 for Sunday, which is just right.
    leadGap = new GregorianCalendar(yy, mm, 1).get(Calendar.DAY_OF_WEEK) - 1;
    // System.out.println("leadGap = " + leadGap);

    int daysInMonth = dom[mm];
    if (isLeap(calendar.get(Calendar.YEAR)) && mm == 1)
//    if (isLeap(calendar.get(Calendar.YEAR)) && mm > 1)
      ++daysInMonth;

    // Blank out the labels before 1st day of month
    for (int i = 0; i < leadGap; i++) {
      labs[0][i].setText("");
    }
    // Fill in numbers for the day of month.
    for (int i = 1; i <= daysInMonth; i++) {
      JButton b = labs[(leadGap + i - 1) / 7][(leadGap + i - 1) % 7];
      b.setText(Integer.toString(i));
        try {
            b.setToolTipText("<html><p>"+((i<=9)?"0"+i:i)+" "+months[mm]+" "+yy+"</p><p>"+_db.getKalendarzDzien(user,i,mm,yy)+"</p></html>");
        } catch (RemoteException ex) {
            Logger.getLogger(Kalendarz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // 7 days/week * up to 6 rows
    for (int i = leadGap + 1 + daysInMonth; i < 6 * 7; i++) {
      labs[(i) / 7][(i) % 7].setText("");
    }

    // Shade current day, only if current month
    if (thisYear == yy && mm == thisMonth)
      setDayActive(dd); // shade the box for today

    // Say we need to be drawn on the screen
    repaint();
  }

  /**
   * isLeap() returns true if the given year is a Leap Year.
   * 
   * "a year is a leap year if it is divisible by 4 but not by 100, except
   * that years divisible by 400 *are* leap years." -- Kernighan & Ritchie,
   * _The C Programming Language_, p 37.
   */
  public boolean isLeap(int year) {
    if (year % 4 == 0 && year % 100 != 0 || year % 400 == 0)
      return true;
    return false;
  }

  /** Set the year, month, and day */
  public void setDate(int yy, int mm, int dd) {
    // System.out.println("Cal::setDate");
    this.yy = yy;
    this.mm = mm; // starts at 0, like Date
    this.dd = dd;
    recompute();
  }

  /** Unset any previously highlighted day */
  private void clearDayActive() {
    JButton b;

    // First un-shade the previously-selected square, if any
    if (activeDay > 0) {
      b = labs[(leadGap + activeDay - 1) / 7][(leadGap + activeDay - 1) % 7];
      b.setBackground(b0.getBackground());
      b.repaint();
      activeDay = -1;
    }
  }

  private int activeDay = -1;

  /** Set just the day, on the current month */
  public void setDayActive(int newDay) {

    clearDayActive();

    // Set the new one
    if (newDay <= 0)
      dd = new GregorianCalendar().get(Calendar.DAY_OF_MONTH);
    else
      dd = newDay;
    // Now shade the correct square
    JButton square = labs[(leadGap + newDay - 1) / 7][(leadGap + newDay - 1) % 7];
    square.setBackground(Color.red);
    
    square.addMouseListener(new MouseAdapter() {

        @Override
        public void mouseClicked(MouseEvent e) {
            final JFrame f=new JFrame("Zaktualizuj notatkę w dniu: "+dd+" "+mm+" "+yy); //To change body of generated methods, choose Tools | Templates.
            Container c = f.getContentPane();
            c.setLayout(new FlowLayout());
            JPanel panel=new JPanel();
            panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS));
            JLabel label1=new JLabel("Wpisz notatkę");
            //panel.setLayout(new BoxLayout(label1, BoxLayout.Y_AXIS));
            final JTextArea area=new JTextArea();
            try {
                if("brak".equals(_db.getKalendarzDzien(user,dd,mm,yy)))
                {
                } else {
                    area.setText(_db.getKalendarzDzien(user,dd,mm,yy));
                }
            } catch (RemoteException ex) {
            }
            JScrollPane scrolpanel=new JScrollPane(area);
            scrolpanel.setPreferredSize(new Dimension(300, 300));
            //panel.setLayout(new BoxLayout(area, BoxLayout.Y_AXIS));
            JButton button=new JButton("Dodaj");
            button.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent e) {
                     //To change body of generated methods, choose Tools | Templates.
                    setToText(user,(dd+"-"+mm+"-"+yy).toString(),area.getText());
                    f.dispose();
                    recompute();
                }
                
            });
           // panel.setLayout(new BoxLayout(button, BoxLayout.Y_AXIS));
            panel.add(label1);
            panel.add(scrolpanel);
            panel.add(button);
            c.add(panel);
            f.setSize(400, 400);
            f.setVisible(true);
        }
        
        
    });
    square.repaint();
    activeDay = newDay;
  }
  void setToText(int user,String date,String text){
      try {
          if(_db.Add_toKalendarz(user,date,text)){
              JOptionPane.showMessageDialog(this, "Dodaj Notatke");
          }else{
              JOptionPane.showMessageDialog(this, "B��d 113");
          }
      } catch (RemoteException ex) {
      }
  }

}
    /*
    private void table(int yearNow,int monthNameNow ,int dayNow ,int dayNameNow){
        
        // Miesiące
        switch(monthNameNow){
                    case GregorianCalendar.JANUARY: monthOfYear = 1;  dayOfMonth = 31; nameMonth = "Styczeń"; break;
                case GregorianCalendar.FEBRUARY:monthOfYear = 2;  dayOfMonth = 28; nameMonth = "Luty";break;
                case GregorianCalendar.MARCH:monthOfYear = 3;  dayOfMonth = 31; nameMonth = "Marzec";break;
                case GregorianCalendar.APRIL:monthOfYear = 4;  dayOfMonth = 30; nameMonth = "Kwiecień";break;
                case GregorianCalendar.MAY:monthOfYear = 5;  dayOfMonth = 31; nameMonth = "Maj";break;
                case GregorianCalendar.JUNE:monthOfYear = 6;  dayOfMonth = 30; nameMonth = "Czerwiec";break;
                case GregorianCalendar.JULY:monthOfYear = 7;  dayOfMonth = 31; nameMonth = "Lipiec";break;
                case GregorianCalendar.AUGUST:monthOfYear = 8;  dayOfMonth = 31; nameMonth = "Sierpień";break;
                case GregorianCalendar.SEPTEMBER:monthOfYear = 9;  dayOfMonth = 30; nameMonth = "Wrzesień";break;
                case GregorianCalendar.OCTOBER:monthOfYear = 10; dayOfMonth = 31; nameMonth = "Październik";break;
                case GregorianCalendar.NOVEMBER:monthOfYear = 11; dayOfMonth = 30; nameMonth = "Listopad";break;
                case GregorianCalendar.DECEMBER:monthOfYear = 12; dayOfMonth = 31; nameMonth = "Grudzień";break;
       }
       switch(dayNameNow){
           case GregorianCalendar.MONDAY:    dayOfWeek = 1;break;
                case GregorianCalendar.TUESDAY:   dayOfWeek = 2;break;
                case GregorianCalendar.WEDNESDAY: dayOfWeek = 3;break;
                case GregorianCalendar.THURSDAY:  dayOfWeek = 4;break;
                case GregorianCalendar.FRIDAY:    dayOfWeek = 5;break;
                case GregorianCalendar.SATURDAY:  dayOfWeek = 6;break;
                case GregorianCalendar.SUNDAY:    dayOfWeek = 7;break;
       }
       miesiac.setText(nameMonth + " "+ yearNow);
       // etykiety dni tygodnia
       
      //jTable2 = new JTable( dataValues, dniTygodnia );
      //jTable2.revalidate();
     // jTable2.repaint();
       String[] tournies = {
            "tournament 1\ntournament 2\n", "tournament 1\n",
            "tournament 1\ntounrament 2\ntournament 3\ntournament 4\n",
            "tournament 1\ntounrament 2\ntournament 3\ntournament 4\n" +
            "tournament 5\ntounrament 6\ntournament 7\ntournament 8\n" +
            "tournament 9\ntounrament 10\ntournament 11\ntournament 12\n"
        };
       String [] dniTygodnia=new String []{"","Poniedziałek","Wtorek","Środa","Czwartek","Piatek","Sobota","Niedziela"};
        DefaultTableModel model = new DefaultTableModel(0, 0);
        for(int i=0;i<dniTygodnia.length;i++){
       model.addColumn(dniTygodnia[i]);
    }
       //
       //model.addRow(dataValues);
        //jTable2.getRowHeight(50);

       
       model.addRow(tournies);
       jTable2.setRowHeight(100);
        jTable2.setPreferredScrollableViewportSize(jTable2.getPreferredSize());
            //jTable2.getColumnModel().getColumn(2).setCellEditor(new MyTableCellEditor());
       jTable2.setModel(model);
        
        for(int i=1;i<dniTygodnia.length;i++){
        jTable2.getColumnModel().getColumn(i).setCellEditor(new CustomEditor(i+""));
        jTable2.getColumnModel().getColumn(i).setCellRenderer(new CustomRenderer(i+""));
        }
        
      int nieparzyste=1;
       GregorianCalendar FirstDateMonth = new GregorianCalendar(yearNow, monthOfYear, 1);
        System.out.print(monthOfYear);
       int day =  (FirstDateMonth.get(Calendar.DAY_OF_WEEK_IN_MONTH)+2)%7;
       System.out.println(day);
       int FirstWeekend = FirstDateMonth.get(Calendar.WEEK_OF_YEAR);
       GregorianCalendar LastDateMonth = new GregorianCalendar(yearNow, monthOfYear, dayOfMonth);
       int LastWeekend = LastDateMonth.get(Calendar.WEEK_OF_YEAR);
       int iloscTygodni=LastWeekend-FirstWeekend;
      //Vector<Object> row = new Vector<Object>();
      
    }
class CustomRenderer implements TableCellRenderer
{
    JScrollPane scrollPane;
    JTextArea textArea;
    JLabel label;
    JPanel listPane;
    public CustomRenderer(String id)
    {
        label=new JLabel(id,label.RIGHT);
        textArea = new JTextArea();
        scrollPane = new JScrollPane(textArea);
        listPane = new JPanel();
        listPane.setLayout(new GridLayout(0,1));
        listPane.add(label);
        listPane.add(scrollPane);
    }
  
    public Component getTableCellRendererComponent(JTable table,
                                                   Object value,
                                                   boolean isSelected,
                                                   boolean hasFocus,
                                                   int row, int column)
    {
        textArea.setText((String)value);
        return listPane;
    }
}
  
class CustomEditor implements TableCellEditor
{
    JScrollPane scrollPane;
    JTextArea textArea;
    JLabel label;
    JPanel listPane;
  
    public CustomEditor(String id)
    {
        label=new JLabel(id,label.RIGHT);
        textArea = new JTextArea();
        scrollPane = new JScrollPane(textArea);
        listPane = new JPanel();
        listPane.setLayout(new GridLayout(0,1));
        listPane.add(label);
        listPane.add(scrollPane);
    }
  
    public Component getTableCellEditorComponent(JTable table,
                                                 Object value,
                                                 boolean isSelected,
                                                 int row, int column)
    {
        textArea.setText((String)value);
        return listPane;
    }
  
    public void addCellEditorListener(CellEditorListener l) { }
    public void cancelCellEditing() { }
    public Object getCellEditorValue()
    {
        return textArea.getText();
    }
    public boolean isCellEditable(EventObject anEvent)
    {
        return true;
    }
    public void removeCellEditorListener(CellEditorListener l) { }
    public boolean shouldSelectCell(EventObject anEvent)
    {
        return true;
    }
    public boolean stopCellEditing()
    {
        return true;
    }
}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
